"""Decide whether a hook payload carries a prompt a human actually typed.

Upstream of the gate and load-bearing for every number downstream. Measured on the first
live gate log: 20 of 27 decisions (74%) were made on text the user never wrote -- task
notifications, system reminders, slash-command caveats and the hook's own injections all
arrive through UserPromptSubmit shaped exactly like a typed message. The ceremonial rate
read 89% against a design target near 40%, almost entirely on that traffic.

The naive form of this filter -- reject any text CONTAINING a harness marker -- was built
first and measured at a 30% false-drop rate on 1,584 real turns, because Claude Code
APPENDS <system-reminder> blocks to messages the user really did type. So the rule is
strip-then-check-residue: remove the wrappers the harness owns, and ask whether anything
human is left. A marker that can only ever be the whole payload (a task notification, a
cross-session delivery, a skill body) rejects outright; a marker that decorates a real
message is stripped and the remainder is judged.

The same mistake in its transcript form already cost this system once: skill bodies are
recorded as role:user and one literally contains "I told you already", so a regex
correction classifier scored 24% precision until the fix went in structurally rather than
as more patterns. Structural again here -- markers the harness emits, never a guess at
what a human "sounds like".

Ambiguity resolves to SYNTHETIC, i.e. to silence. A missed real prompt costs one un-scoped
turn; a missed synthetic one costs ceremony on every notification for the rest of the
session, and feeds the gate its own exhaust.
"""

from __future__ import annotations

import re

#: Blocks the harness wraps AROUND text that may still be a real human message. Stripped,
#: not rejected -- see the module docstring for the 30% false-drop this cost.
_STRIPPABLE = (
    re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL | re.IGNORECASE),
    re.compile(
        r"<local-command-(caveat|stdout|stderr)>.*?</local-command-\1>", re.DOTALL | re.IGNORECASE
    ),
    re.compile(r"<command-(name|message|args)>.*?</command-\1>", re.DOTALL | re.IGNORECASE),
    re.compile(
        r"^\s*Caveat: The messages below were generated by the user[^\n]*\n?",
        re.IGNORECASE | re.MULTILINE,
    ),
)

#: Markers that can only be the WHOLE payload. Their presence anywhere rejects the turn --
#: there is no version of these that is also a human request.
_WHOLE_PAYLOAD = (
    "[system notification - not user input]",
    "<task-notification>",
    "this is an automated background-task event",
    "<cross-session-message",
    "another claude session sent a message:",
    "[cross-session delivery notice]",
    "this session is being continued from a previous conversation",
    "stop hook feedback:",
    "userpromptsubmit hook success:",
    "base directory for this skill:",
    "continue from where you left off.",
    "<budget:",
    "<command-name>",  # slash-command invocation; the gate returns NONE for these
    "[image:",  # pasted screenshot header, not a typed request
    "goal check-in:",
    "a session-scoped stop hook is now active with condition:",  # /loop's own injection
)

#: Structural shape of a skill/reference-doc dump landing verbatim as a "user" turn: an H1
#: title line followed later by at least one "##" subsection, long enough to be a document
#: rather than a one-line markdown-formatted request. Matched on SHAPE, not on any skill's
#: title, so a newly-shipped skill leaks nothing without this list ever being touched --
#: the alternative (blacklisting titles like "# Workflow authoring reference") rots the
#: moment a new skill ships.
_DOC_HEADING = re.compile(r"\A\s*#{1,2}[ \t]+\S")
_MIN_DOC_CHARS = 300


def _is_skill_doc_shape(text: str) -> bool:
    return bool(_DOC_HEADING.match(text)) and "\n##" in text and len(text) > _MIN_DOC_CHARS


#: The hook's own output read back in. A gate scoring its own injections is a feedback loop
#: built out of its own exhaust.
_SELF = ("[scope:",)

#: Below this many characters of residue there is no request left to scope -- what remains
#: is punctuation and whitespace from the stripped wrappers.
MIN_RESIDUE_CHARS = 1


def human_residue(prompt: str) -> str:
    """The prompt with every harness-owned wrapper removed."""
    text = prompt or ""
    for pattern in _STRIPPABLE:
        text = pattern.sub(" ", text)
    return text.strip()


def synthetic_reason(prompt: str) -> str | None:
    """Why this text is not a human turn, or None if it is one.

    Returns the marker that fired, so a suppressed decision stays auditable: a filter that
    drops traffic silently is indistinguishable from a filter that is broken.
    """
    low = (prompt or "").lower()
    for marker in _SELF:
        if marker in low:
            return f"the hook's own injection ({marker!r})"
    for marker in _WHOLE_PAYLOAD:
        if marker in low:
            return f"harness-generated payload ({marker!r})"
    if _is_skill_doc_shape(prompt or ""):
        return "skill/reference-doc body (heading + subsections, not a typed request)"
    if len(human_residue(prompt)) < MIN_RESIDUE_CHARS:
        return "nothing left after stripping harness wrappers"
    return None


def is_human_prompt(prompt: str) -> bool:
    return synthetic_reason(prompt) is None
